#!/bin/sh
jarsigner -keystore developer.keystore -storepass password "$1" dktest
jarsigner -keystore developer.keystore -storepass password "$1" ditest
jarsigner -keystore developer.keystore -storepass password "$1" dntest
